### ISSUE TITLE
IndexError raised during initial config

### ISSUE THREAD

**Issue by jtfidje** [firecat53/bitwarden-menu#23]
During initial config after install / when no config file exist, `IndexError` is raised after the following steps:

1. [Enter] for default URL
2. Input my email. [Enter]
3. [Enter] for `None` 2FA  <-- This raises the exception.

```
Traceback (most recent call last):
  File "/home/jtfidje/.local/lib/python3.10/site-packages/bwm/__main__.py", line 174, in main
    manager = client()
  File "/home/jtfidje/.local/lib/python3.10/site-packages/bwm/__main__.py", line 79, in client
    mgr.connect()
  File "/usr/lib/python3.10/multiprocessing/managers.py", line 531, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 507, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 635, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jtfidje/.local/bin/bwm", line 8, in <module>
    sys.exit(main())
  File "/home/jtfidje/.local/lib/python3.10/site-packages/bwm/__main__.py", line 181, in main
    run(**args)
  File "/home/jtfidje/.local/lib/python3.10/site-packages/bwm/__main__.py", line 129, in run
    dmenu = DmenuRunner(server, **kwargs)
  File "/home/jtfidje/.local/lib/python3.10/site-packages/bwm/bwm.py", line 382, in __init__
    self.vaults = get_vault(**kwargs)
  File "/home/jtfidje/.local/lib/python3.10/site-packages/bwm/bwm.py", line 114, in get_vault
    vaults[0] = sel
IndexError: list assignment index out of range
```

**Comment by firecat53** [comment]
I'm really sorry I missed this report! I've not been paying very close attention to my various projects for the past several months. I can reproduce this, so I'll work on it as soon as I can. Thanks for the interest!

**Comment by firecat53** [comment]
Well, hopefully it was that easy to fix! Let me know if that works for you if you've had the patience to wait for me this long!!

**Comment by jtfidje** [comment]
Hi! So sorry I did not answer you last time! It works perfectly on the develop branch 🙂 Thank you for fixing !
