### ISSUE TITLE
BWM Hangs at Password Selection

### ISSUE THREAD

**Issue by TomRobinsonIO** [firecat53/bitwarden-menu#28]
Hello,

bwm hangs at attempting to select an entry from my password list. When attempting to run bwm from the terminal, the menu will display all of the entries in my vault and allow me to search through them. When hitting enter, the launcher window (Wofi in my case, but also tried with dmenu) goes away. After waiting any amount of time and interrupting with ctrl+c, the terminal outputs the following errors below. Please let me know if you require any additional information from me. Thank you in advance for taking a look at my issue.

I am using: 

Fedora 39
Hyprland (wl-roots)
wl-clipboard 2.2.0
wofi v1.3
Python 3.12.0
pip 23.2.1

```
Traceback (most recent call last):
  File "/home/tom/.local/lib/python3.12/site-packages/bwm/__main__.py", line 174, in main
    manager = client()
              ^^^^^^^^
  File "/home/tom/.local/lib/python3.12/site-packages/bwm/__main__.py", line 79, in client
    mgr.connect()
  File "/usr/lib64/python3.12/multiprocessing/managers.py", line 531, in connect
    conn = Client(self._address, authkey=self._authkey)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/multiprocessing/connection.py", line 501, in Client
    c = SocketClient(address)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/multiprocessing/connection.py", line 629, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tom/.local/bin//bwm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/tom/.local/lib/python3.12/site-packages/bwm/__main__.py", line 181, in main
    run(**args)
  File "/home/tom/.local/lib/python3.12/site-packages/bwm/__main__.py", line 133, in run
    server.join()
  File "/usr/lib64/python3.12/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Process Server-1:
Traceback (most recent call last):
  File "/home/tom/.local/lib/python3.12/site-packages/bwm/__main__.py", line 174, in main
    manager = client()
              ^^^^^^^^
  File "/home/tom/.local/lib/python3.12/site-packages/bwm/__main__.py", line 79, in client
    mgr.connect()
  File "/usr/lib64/python3.12/multiprocessing/managers.py", line 531, in connect
    conn = Client(self._address, authkey=self._authkey)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/multiprocessing/connection.py", line 501, in Client
    c = SocketClient(address)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/multiprocessing/connection.py", line 629, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/tom/.local/lib/python3.12/site-packages/bwm/__main__.py", line 100, in run
    self.kill_flag.wait()
  File "/usr/lib64/python3.12/multiprocessing/synchronize.py", line 356, in wait
    self._cond.wait(timeout)
  File "/usr/lib64/python3.12/multiprocessing/synchronize.py", line 268, in wait
    return self._wait_semaphore.acquire(True, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by firecat53** [comment]
My initial thought is perhaps a python 3.12 error. It hasn't been tested on 3.12 yet. I'll have to look into that. Thanks for the report!

**Comment by TomRobinsonIO** [comment]
Thanks for the quick reply! Do you have a recommended python version?

**Comment by firecat53** [comment]
I know it works on 3.11, although I'm not guaranteeing that the 3.12 upgrade is actually the cause of the bug 🙂

**Comment by firecat53** [comment]
Ah.  After reading your bug again, I think you don't have a type_library specified in your config file so nothing is typed when you hit enter. You need to install and configure wtype or ydotool and add that to your config (see the docs). The error messages are just because you exited the program (I haven't cleaned that up yet like I have in keepmenu).

Let me know if that works for you.

**Comment by TomRobinsonIO** [comment]
It is very possible this is related to ydotool. I have ```type_library = ydotool``` in my config.ini file. I can run a ydotool command like "ydotool mousemove -x -100 -y 100" and the mouse will move. I did however notice that the ydotool service is listed as failed in systemctl list-units. Would that service be required for bwm to work?

**Comment by firecat53** [comment]
(Sorry for the delayed response)

Yes, you will need ydotool (or xdotool if you're not using Wayland) to type entries unless you only use the clipboard feature, in which case you will need the `wl-clipboard` package. Ydotoold [must be running](https://github.com/ReimuNotMoe/ydotool#why-a-background-service-is-needed).

On NixOS, here's the very simple user service I use (should be very similar on other distros):

```
❯ systemctl --user cat ydotool.service
# /home/firecat53/.config/systemd/user/ydotool.service
[Service]
ExecStart=/nix/store/55xirg2dybjin2k6jx5dvnnk0pgmivjg-ydotool-1.0.4/bin/ydotoold

[Unit]
Description=Start ydotoold
```  
And here's the module that generates that:
```
{
  pkgs,
  ...
}:{
  # Note: /dev/uinput needs 'user' group access. Add this to udev rules (or
  # system Nix config):
  #  services.udev.extraRules = ''
  #    KERNEL=="uinput", GROUP="users", MODE="0660",  OPTIONS+="static_node=uinput"
  #  '';
  systemd.user.services = {
    ydotool = {
      Unit = {
        Description = "Start ydotoold";
      };
      Service = {
        ExecStart = "${pkgs.ydotool}/bin/ydotoold";
      };
    };
  };
}
```

**Comment by firecat53** [comment]
Were you ever able to get this working? Thanks!

**Comment by TomRobinsonIO** [comment]
Hey @firecat53, no, unfortunately not. I know that ydotool is functioning properly as a service now, but I wasn't ever able to get past the same point in the process as before.

**Comment by TomRobinsonIO** [comment]
I was finally able to get this working today. A new issue cropped up after updating python3. 

`Traceback (most recent call last):
  File "/home/tom/.local/bin//bwm", line 5, in <module>
    from bwm.__main__ import main
  File "/home/tom/.local/lib/python3.12/site-packages/bwm/__init__.py", line 15, in <module>
    from xdg import XDG_CACHE_HOME, XDG_CONFIG_HOME, XDG_DATA_HOME`

Doing a little digging through the repo, I see one of your latest commits was to [Convert from xdg to xdg-base-dirs](https://github.com/firecat53/bitwarden-menu/commit/55492247ddbca5939b886c1f56627df2fdad9ae5), but upgrading from pip didn't pull anything. I think my problems may be related to the fact that the version on pypi hasn't been updated since 2022. [bitwarden-menu 0.4.1](https://pypi.org/project/bitwarden-menu/#history).

I uninstalled from pip and then installed using the documentation to pull from git and install editable from the cloned folder. I don't think there's a command to tell exactly what version I'm running, but it looks like I was running 0.4.1 before from pip and the install logs from git indicate I'm not on 0.4.2.dev22 and working as intended.

**Comment by firecat53** [comment]
I just pushed a commit to the `develop` branch with some wofi-friendly changes.  You don't need to add the `--dmenu` flag in your config as bwm does that for you. E.g.  `dmenu_command = wofi -i -L 10`

Give the changes a try and let me know if it works for you. Thanks!
